GET http://localhost:3000/subscriber HTTP/1.1

###

GET http://localhost:3000/subscriber/618c7a0b3f6cf69ae4fb83a4 HTTP/1.1

###

POST http://localhost:3000/subscriber HTTP/1.1
Content-Type: application/json

{
    "name": "Amazing Person",
    "subscribedToChannel": "We Dev Simplified"
}

###

DELETE http://localhost:3000/subscriber/618c7a0b3f6cf69ae4fb83a4 HTTP/1.1

###
PATCH  http://localhost:3000/subscriber/618c7d2091a701606683aa8a HTTP/1.1
Content-Type: application/json

{
    "name": "New Name"
}